import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const sourceHanSans = localFont({
  src: './font/SourceHanSans-VF.otf',
  variable: "--font-shs",
  display: "swap",
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='min-h-full min-w-full'>
      <body className={`${sourceHanSans.className} min-h-full min-w-full`}>{children}</body>
    </html>
  )
}
